###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  webserver:
    container_name: 'php-lol-web'
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    networks:
      - php-lol
    depends_on:
      - php-fpm
      - memcached
      - mailhog
      - redis
      - mysql
      - meilisearch

  php-fpm:
    container_name: 'php-lol-php'
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    networks:
      - php-lol

  memcached:
    container_name: 'php-lol-memcached'
    image: 'memcached:alpine'
    networks:
      - php-lol

  mailhog:
    container_name: 'php-lol-mailhog'
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - php-lol

  redis:
    container_name: 'php-lol-redis'
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'php-lol-redis:/data'
    networks:
      - php-lol
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  mysql:
    container_name: 'php-lol-mysql'
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - 'php-lol-mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=$(DB_DATABASE)
      - MYSQL_USER=$(DB_USER)
      - MYSQL_PASSWORD=$(DB_PASSWORD)
    ports:
      - '8082:3306'
    networks:
      - php-lol
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  meilisearch:
    container_name: 'php-lol-meilisearch'
    image: 'getmeili/meilisearch:latest'
    ports:
      - '7700:7700'
    volumes:
      - 'php-lol-meilisearch:/meili_data'
    networks:
      - php-lol
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health" ]
      retries: 3
      timeout: 5s

networks:
  php-lol:
    driver: bridge

volumes:
  php-lol-mysql:
    driver: local
  php-lol-redis:
    driver: local
  php-lol-meilisearch:
    driver: local
